name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted

    env:
      NODE_TAG: 22.14-alpine3.21

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: petitgens/caneton-arbitre:latest
        build-args: |
          NODE_TAG=${{ env.NODE_TAG }}
